import { Link } from "@mui/material";
import React from "react";
import FAQContent from "../../../../Common/FAQ/FAQContent";

const FaqData = [
  {
    title: "What is Mintoria?",
    content: (
      <>
        <FAQContent
          key={"a11"}
          text={`
          Mintoria is a generative art community hosted on the blockchain that
          helps in building the next iteration of art. Our focus is on storing
          immutably and generating on-demand generative content.`}
        />
        <FAQContent
          key={"a12"}
          text={`
          The artist's and collectors' journeys are forever intertwined, as the
          generating of the content is partnership: the artist establishes the
          styles and rules of the content, while the collector introduces
          entropy through minting. Each output is different, wrapped in an
          ERC721 token and sent to your ETH account.`}
        />
      </>
    ),
  },
  {
    title: "What is Mintoria Selected?",
    content: (
      <>
        <FAQContent
          key={"a21"}
          text={`Selected is Mintoria's gallery of curated projects. The projects represent our vision and our participation in the evolution of generative art.`}
        />
        <FAQContent
          key={"a22"}
          text={`Projects are grouped in series that are released quartlerly.`}
        />
      </>
    ),
  },
  {
    title: "What is Mintoria Open World",
    content: (
      <>
        <FAQContent
          key={"a31"}
          text={`Open World was designed for artists that do not want to submit their project through the curation process.
      This allows artists to release their art to the world as quickly as possible and be part of our community.`}
        />
        <FAQContent
          key={"a32"}
          text={`Requirements are very relaxed compared to the curated projects, and focus more on the integrity and correctness of the work.`}
        />
      </>
    ),
  },
  {
    title: "What are the supported wallets?",
    content: (
      <>
        <FAQContent
          key={"a41"}
          text={`Mintoria is in essence a decentralised, web3.0 platform so all wallets can interact with our platform.`}
        />
        <FAQContent
          key={"a42"}
          text={`However our front-end only supports Metamask at the moment. We will release further integrations with other wallets like WalletConnect in the near future`}
        />
      </>
    ),
  },
  {
    title: "How do I mint?",
    content: (
      <>
        <FAQContent
          key={"a51"}
          text={`Minting on Mintoria is easy and fun! Seeing how art is born, unique, on-demand and with your participation is a great experience.`}
        />
        <FAQContent
          key={"a52"}
          text={
            <>
              <span>
                You'll need the Metamask extension installed in your browser, so
                if you don't have it, visit
              </span>{" "}
              <Link href="https://metamask.io/" target={"_blank"}>
                https://metamask.io
              </Link>{" "}
              <span>to install it.</span>
            </>
          }
        />
        <FAQContent
          key={"a53"}
          text={`To start minting your tokens, navigate to a project page you enjoy and click the Mint button.
          Next, confirm the Metamask purchase transaction (both the purchase price and the gas fees are displayed).
          After the transaction is confirmed, you'll be presented with your piece of generative art, your ERC721 token stored on the Ethereum blockchain. Congratulations!`}
        />
      </>
    ),
  },
  {
    title: "Can I resell my tokens on OpenSea?",
    content: (
      <>
        <FAQContent
          key={"a61"}
          text={`Yes. The tokens generated by the Mintoria smart contracts are ERC721 compatible, meaning you can list your tokens immediately after minting.`}
        />
      </>
    ),
  },
  {
    title: "How is rarity calculated?",
    content: (
      <>
        <FAQContent
          key={"a71"}
          text={`The rarity score for a token is calculated using the following formula:`}
        />
        <FAQContent
          key={"a72"}
          text={
            <i>
              [rarity score for a trait] = 1 / ([number of tokens that have the
              trait] / [total number of tokens from the project])
            </i>
          }
        />
        <FAQContent
          key={"a73"}
          text={`So the rarity score for a token equals the sum of the rarity score of its traits. The higher the score, the rarer the token.`}
        />
        <FAQContent
          key={"a74"}
          text={
            <i>Note: rarity is computed only for completed mainnet projects.</i>
          }
        />
      </>
    ),
  },
  {
    title: "How do I get more information?",
    content: (
      <>
        <FAQContent
          key={"a81"}
          text={
            <>
              <span>
                We have prepared extensive documentation for collectors:
              </span>{" "}
              <Link
                href="https://docs.mintoria.io/"
                target="_blank"
                rel="noreferrer"
              >
                Mintoria Docs
              </Link>
            </>
          }
        />
        <FAQContent
          key={"a82"}
          text={
            <>
              <span>
                You can also join our Discord community of artists and
                collectors. Here you'll b able to reach out for help, but also
                have conversations over generative art and other topics. It's
                the place to be!
              </span>{" "}
              <br /> <br />
              <Link
                href="https://discord.gg/SudxZYSzKK"
                target="_blank"
                rel="noreferrer"
              >
                Join our Discord server
              </Link>
            </>
          }
        />
      </>
    ),
  },
];

export default FaqData;
